using System.Text;
using System.Xml.Linq;

namespace ResxL10n;

internal sealed record ResxEntry(string Key, string Value, string? Comment);

internal static class ResxFile
{
    private static readonly XName DataName = "data";
    private static readonly XName ValueName = "value";
    private static readonly XName CommentName = "comment";

    public static string SourceFileName => "Strings.resx";

    public static string SatelliteFileName(string culture) => $"Strings.{culture}.resx";

    public static IReadOnlyDictionary<string, ResxEntry> ReadEntries(string path)
    {
        if (!File.Exists(path))
            return new Dictionary<string, ResxEntry>(StringComparer.Ordinal);

        var doc = XDocument.Load(path, LoadOptions.PreserveWhitespace);
        if (doc.Root is null)
            return new Dictionary<string, ResxEntry>(StringComparer.Ordinal);

        return doc.Root
            .Elements(DataName)
            .Select(ParseEntry)
            .Where(e => e is not null)
            .Cast<ResxEntry>()
            .ToDictionary(e => e.Key, e => e, StringComparer.Ordinal);
    }

    public static bool WriteUpdates(string path, IReadOnlyDictionary<string, string> valuesByKey, bool isSource)
    {
        if (!File.Exists(path))
        {
            if (!isSource)
            {
                CreateSatelliteFile(path, valuesByKey);
                return true;
            }

            throw new FileNotFoundException($"Source resource file not found: {path}");
        }

        var existing = ReadEntries(path);
        if (!HasChanges(existing, valuesByKey))
            return false;

        var doc = XDocument.Load(path, LoadOptions.PreserveWhitespace);
        var root = doc.Root ?? throw new InvalidOperationException($"Invalid resx file (no root): {path}");

        foreach (var (key, value) in valuesByKey)
        {
            var data = root.Elements(DataName)
                .FirstOrDefault(e => string.Equals(e.Attribute("name")?.Value, key, StringComparison.Ordinal));

            if (data is null)
            {
                if (string.IsNullOrEmpty(value))
                    continue;

                root.Add(CreateDataElement(key, value));
                continue;
            }

            if (string.IsNullOrEmpty(value))
            {
                data.Remove();
                continue;
            }

            var valueElement = data.Element(ValueName);
            if (valueElement is null)
                data.Add(new XElement(ValueName, value));
            else
                valueElement.Value = value;
        }

        Save(doc, path);
        return true;
    }

    private static bool HasChanges(
        IReadOnlyDictionary<string, ResxEntry> existing,
        IReadOnlyDictionary<string, string> valuesByKey)
    {
        foreach (var (key, value) in valuesByKey)
        {
            if (!existing.TryGetValue(key, out var entry))
            {
                if (!string.IsNullOrEmpty(value))
                    return true;
                continue;
            }

            if (!string.Equals(entry.Value, value, StringComparison.Ordinal))
                return true;
        }

        return false;
    }

    private static void CreateSatelliteFile(string path, IReadOnlyDictionary<string, string> valuesByKey)
    {
        var doc = new XDocument(
            new XElement("root",
                new XComment(
                    " Generated by scripts/resx-l10n. Only translated keys belong here; " +
                    "missing keys fall back to Strings.resx. "),
                CreateSchema(),
                CreateResHeader("resmimetype", "text/microsoft-resx"),
                CreateResHeader("version", "2.0"),
                CreateResHeader("reader",
                    "System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"),
                CreateResHeader("writer",
                    "System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"),
                valuesByKey
                    .Where(kv => !string.IsNullOrEmpty(kv.Value))
                    .OrderBy(kv => kv.Key, StringComparer.Ordinal)
                    .Select(kv => CreateDataElement(kv.Key, kv.Value))));

        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        Save(doc, path);
    }

    private static ResxEntry? ParseEntry(XElement data)
    {
        var key = data.Attribute("name")?.Value;
        if (string.IsNullOrEmpty(key))
            return null;

        return new ResxEntry(
            key,
            data.Element(ValueName)?.Value ?? string.Empty,
            data.Element(CommentName)?.Value);
    }

    private static XElement CreateDataElement(string key, string value) =>
        new(DataName,
            new XAttribute("name", key),
            new XAttribute(XNamespace.Xml + "space", "preserve"),
            new XElement(ValueName, value));

    private static XElement CreateResHeader(string name, string value) =>
        new("resheader",
            new XAttribute("name", name),
            new XElement("value", value));

    private static XElement CreateSchema()
    {
        const string schema = """
            <xsd:schema id="root" xmlns="" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
              <xsd:import namespace="http://www.w3.org/XML/1998/namespace" />
              <xsd:element name="root" msdata:IsDataSet="true">
                <xsd:complexType>
                  <xsd:choice maxOccurs="unbounded">
                    <xsd:element name="metadata">
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element name="value" type="xsd:string" minOccurs="0" />
                        </xsd:sequence>
                        <xsd:attribute name="name" use="required" type="xsd:string" />
                        <xsd:attribute name="type" type="xsd:string" />
                        <xsd:attribute name="mimetype" type="xsd:string" />
                        <xsd:attribute ref="xml:space" />
                      </xsd:complexType>
                    </xsd:element>
                    <xsd:element name="assembly">
                      <xsd:complexType>
                        <xsd:attribute name="alias" type="xsd:string" />
                        <xsd:attribute name="name" type="xsd:string" />
                      </xsd:complexType>
                    </xsd:element>
                    <xsd:element name="data">
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
                          <xsd:element name="comment" type="xsd:string" minOccurs="0" msdata:Ordinal="2" />
                        </xsd:sequence>
                        <xsd:attribute name="name" type="xsd:string" use="required" msdata:Ordinal="1" />
                        <xsd:attribute name="type" type="xsd:string" msdata:Ordinal="3" />
                        <xsd:attribute name="mimetype" type="xsd:string" msdata:Ordinal="4" />
                        <xsd:attribute ref="xml:space" />
                      </xsd:complexType>
                    </xsd:element>
                    <xsd:element name="resheader">
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
                        </xsd:sequence>
                        <xsd:attribute name="name" type="xsd:string" use="required" />
                      </xsd:complexType>
                    </xsd:element>
                  </xsd:choice>
                </xsd:complexType>
              </xsd:element>
            </xsd:schema>
            """;

        return XElement.Parse(schema);
    }

    private static void Save(XDocument doc, string path)
    {
        var settings = new System.Xml.XmlWriterSettings
        {
            Encoding = new UTF8Encoding(encoderShouldEmitUTF8Identifier: true),
            Indent = true,
            OmitXmlDeclaration = false,
        };

        using var writer = System.Xml.XmlWriter.Create(path, settings);
        doc.Save(writer);
    }
}
