// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VideoArchiveManager.Data;

#nullable disable

namespace VideoArchiveManager.Data.Migrations
{
    [DbContext(typeof(VideoArchiveDbContext))]
    [Migration("20260604120000_AddAiEmbeddings")]
    partial class AddAiEmbeddings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("VideoArchiveManager.Core.Models.AiClipEmbedding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Dim")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FrameCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("VideoItemId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Vector")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("VideoItemId")
                        .IsUnique();

                    b.ToTable("AiClipEmbeddings", (string)null);
                });

            modelBuilder.Entity("VideoArchiveManager.Core.Models.AiFrameEmbedding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dim")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<double>("TimeSeconds")
                        .HasColumnType("REAL");

                    b.Property<int>("VideoItemId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Vector")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("VideoItemId");

                    b.ToTable("AiFrameEmbeddings", (string)null);
                });

            modelBuilder.Entity("VideoArchiveManager.Core.Models.AiTagSuggestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Approved")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("BestFrameSeconds")
                        .HasColumnType("REAL");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("VideoItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("State");

                    b.HasIndex("TagName");

                    b.HasIndex("VideoItemId");

                    b.HasIndex("VideoItemId", "TagName")
                        .IsUnique();

                    b.ToTable("AiTagSuggestions", (string)null);
                });

            modelBuilder.Entity("VideoArchiveManager.Core.Models.GeocodeCacheEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<double>("LatRounded")
                        .HasColumnType("REAL");

                    b.Property<string>("LocationShort")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<double>("LonRounded")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("LookedUpAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "LatRounded", "LonRounded")
                        .IsUnique();

                    b.ToTable("GeocodeCacheEntries", (string)null);
                });

            modelBuilder.Entity("VideoArchiveManager.Core.Models.MomentTag", b =>
                {
                    b.Property<int>("VideoMomentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("VideoMomentId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("MomentTags", (string)null);
                });

            modelBuilder.Entity("VideoArchiveManager.Core.Models.RootFolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastScannedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("RootFolders", (string)null);
                });

            modelBuilder.Entity("VideoArchiveManager.Core.Models.SavedSearch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CriteriaJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SavedSearches", (string)null);
                });

            modelBuilder.Entity("VideoArchiveManager.Core.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Type");

                    b.HasIndex("Name", "Type")
                        .IsUnique();

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("VideoArchiveManager.Core.Models.VideoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Camera")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Codec")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContextText")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtFile")
                        .HasColumnType("TEXT");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<bool>("FileExists")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FolderDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FolderPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<double?>("FrameRate")
                        .HasColumnType("REAL");

                    b.Property<double?>("GpsLatitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("GpsLongitude")
                        .HasColumnType("REAL");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocationText")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAtFile")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThumbnailPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Camera");

                    b.HasIndex("FileExists");

                    b.HasIndex("FilePath")
                        .IsUnique();

                    b.HasIndex("FolderDate");

                    b.HasIndex("FolderPath");

                    b.HasIndex("Rating");

                    b.HasIndex("Status");

                    b.ToTable("VideoItems", (string)null);
                });

            modelBuilder.Entity("VideoArchiveManager.Core.Models.VideoMoment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("EndSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("Label")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<double>("StartSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("ThumbnailPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("VideoItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Rating");

                    b.HasIndex("StartSeconds");

                    b.HasIndex("VideoItemId");

                    b.ToTable("VideoMoments", (string)null);
                });

            modelBuilder.Entity("VideoArchiveManager.Core.Models.VideoTag", b =>
                {
                    b.Property<int>("VideoItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("VideoItemId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("VideoTags", (string)null);
                });

            modelBuilder.Entity("VideoArchiveManager.Core.Models.AiClipEmbedding", b =>
                {
                    b.HasOne("VideoArchiveManager.Core.Models.VideoItem", "VideoItem")
                        .WithMany()
                        .HasForeignKey("VideoItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VideoItem");
                });

            modelBuilder.Entity("VideoArchiveManager.Core.Models.AiFrameEmbedding", b =>
                {
                    b.HasOne("VideoArchiveManager.Core.Models.VideoItem", "VideoItem")
                        .WithMany()
                        .HasForeignKey("VideoItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VideoItem");
                });

            modelBuilder.Entity("VideoArchiveManager.Core.Models.AiTagSuggestion", b =>
                {
                    b.HasOne("VideoArchiveManager.Core.Models.VideoItem", "VideoItem")
                        .WithMany()
                        .HasForeignKey("VideoItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VideoItem");
                });

            modelBuilder.Entity("VideoArchiveManager.Core.Models.MomentTag", b =>
                {
                    b.HasOne("VideoArchiveManager.Core.Models.Tag", "Tag")
                        .WithMany("MomentTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoArchiveManager.Core.Models.VideoMoment", "VideoMoment")
                        .WithMany("MomentTags")
                        .HasForeignKey("VideoMomentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("VideoMoment");
                });

            modelBuilder.Entity("VideoArchiveManager.Core.Models.VideoMoment", b =>
                {
                    b.HasOne("VideoArchiveManager.Core.Models.VideoItem", "VideoItem")
                        .WithMany("Moments")
                        .HasForeignKey("VideoItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VideoItem");
                });

            modelBuilder.Entity("VideoArchiveManager.Core.Models.VideoTag", b =>
                {
                    b.HasOne("VideoArchiveManager.Core.Models.Tag", "Tag")
                        .WithMany("VideoTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoArchiveManager.Core.Models.VideoItem", "VideoItem")
                        .WithMany("VideoTags")
                        .HasForeignKey("VideoItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("VideoItem");
                });

            modelBuilder.Entity("VideoArchiveManager.Core.Models.Tag", b =>
                {
                    b.Navigation("MomentTags");

                    b.Navigation("VideoTags");
                });

            modelBuilder.Entity("VideoArchiveManager.Core.Models.VideoItem", b =>
                {
                    b.Navigation("Moments");

                    b.Navigation("VideoTags");
                });

            modelBuilder.Entity("VideoArchiveManager.Core.Models.VideoMoment", b =>
                {
                    b.Navigation("MomentTags");
                });
#pragma warning restore 612, 618
        }
    }
}
