using VideoArchiveManager.Core.Models.Enums;

namespace VideoArchiveManager.Core.Models;

// One AI-proposed tag for a clip, surfaced in the review queue as an
// accept/reject chip. Generated by scoring CLIP image embeddings of sampled
// frames against a label vocabulary; never auto-applied — a suggestion only
// becomes a real Tag/VideoTag when the user accepts it.
public class AiTagSuggestion
{
    public int Id { get; set; }

    public int VideoItemId { get; set; }
    public VideoItem VideoItem { get; set; } = null!;

    public string TagName { get; set; } = string.Empty;

    // Cosine similarity (CLIP image↔text) of the best-matching sampled frame,
    // roughly 0..1. Higher = more confident. Used to rank the review queue.
    public double Confidence { get; set; }

    // Timestamp (seconds) of the sampled frame that matched this label best,
    // so the review UI can jump straight to where the subject appears and,
    // later, spin a suggestion into a Moment. Null if unknown.
    public double? BestFrameSeconds { get; set; }

    // e.g. the CLIP model id that produced this suggestion ("clip-vit-b32").
    public string? Source { get; set; }

    // Retained for backward compatibility with the original (dormant) schema.
    // New code drives the review queue off State; Approved mirrors
    // State == Accepted on write.
    public bool Approved { get; set; }

    public AiSuggestionState State { get; set; } = AiSuggestionState.Pending;

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
}
